// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SLCDM.Persistence;

#nullable disable

namespace SLCDM.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904183000_AddActivoPerifericosAdicionales")]
    partial class AddActivoPerifericosAdicionales
    {
    }
}
