// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SLCDM.Persistence;

#nullable disable

namespace SLCDM.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907233000_AddResponsableDpi")]
    partial class AddResponsableDpi
    {
    }
}
