namespace SLCDM.Application.Features.Activos;

public sealed record ActivoDto(
    int Id,
    int IdCategoriaActivo,
    int IdProveedor,
    int IdUbicacion,
    string Nombre,
    string? Descripcion,
    string? Marca,
    string? Modelo,
    string? NumeroSerie,
    DateTime FechaCompra,
    decimal CostoAdquisicion,
    string? Moneda,
    string? NumeroFactura,
    DateTime FechaVencimientoGarantia,
    string? Observaciones,
    string EstadoOperativo = "disponible",
    string EstadoNombre = "Disponible",
    string CodigoInterno = "",
    int? IdEmpresa = null,
    string? NombreEmpresa = null,
    int? IdSede = null,
    string? NombreSede = null,
    string? NombreUbicacion = null,
    string? NombreArea = null,
    int? IdResponsable = null,
    string? NombreResponsable = null);
